### ISSUE TITLE
Promise error

### ISSUE THREAD

**Issue by CarMasAssistDigital** [jeffbaldwinjr/node-eloqua-sdk#9]
I'm trying to get the campaign from Eloqua with the sample code proposed (all the versions proposed on the home page) but i get the following error:

E5 version:
`TypeError: Cannot read property 'base' of undefined
    at requestPromise.then.response (C:\Users\Carmine\Desktop\nodeWin\testEloquaDelete\node_modules\eloqua-sdk\dist\Eloqua.js:189:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

E6 version (error on import EloquaApi):
`(function (exports, require, module, __filename, __dirname) { import EloquaApi from 'eloqua-sdk';
                                                                     ^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)`

E7 version (error on import EloquaApi):

(function (exports, require, module, __filename, __dirname) { import EloquaApi from 'eloqua-sdk';
                                                                     ^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

I created a simple app.js file and launched with node app.js

**Comment by CarMasAssistDigital** [comment]
Solved by update the password on Eloqua.
Sorry.
